name: "Deploy"
on:
  push:
      tags:
        - "v*"

env:
  EXPORT_NAME: Click

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        run: |
          mkdir -v -p build/windows
          godot -v --export-release --headless "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows
