name: "Deploy"
on: 
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  GODOT_VERSION: 4.1.1
  EXPORT_NAME: Click
  BUTLER_API_KEY: ${{secrets.BUTLER_API_KEY}}

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows"
            preset: "Windows Desktop"
            executable: "Click.exe"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Export
        run: |
          mkdir -v -p build/${{matrix.platform}}
          godot -v --export-release --headless ${{matrix.preset}} build/${{matrix.platform}}/${{matrix.executable}}
      - name: Compress files
        working-directory: build
        run: zip -r ${{matrix.platform}}.zip ${{matrix.platform}}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.platform}}
          path: build/${{matrix.platform}}.zip
          if-no-files-found: error

  deploy-github:
    name: Deploy GitHub
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: windows
          path: build
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows.zip
      - name: Deploy to Itch.io
        run: butler push build/windows.zip ${{vars.ITCHIO_USERNAME}}/${{vars.ITCHIO_GAME}}:windows

  deploy-itchio:
    name: Deploy Itch.io
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    strategy:
      fail-fast: false
      matrix:
        platform: ["windows", "web"]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: web
          path: build
      - name: Deploy to Itch.io
        run: butler push build/${{matrix.platform}}.zip ${{vars.ITCHIO_USERNAME}}/${{vars.ITCHIO_GAME}}:${{matrix.platform}}
