name: "Deploy"
on: 
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  GODOT_VERSION: 4.1.1
  EXPORT_NAME: Click
  BUTLER_API_KEY: ${{secrets.BUTLER_API_KEY}}

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Export
        run: |
          mkdir -v -p build/windows
          godot -v --export-release --headless "Windows Desktop" build/windows/$EXPORT_NAME.exe
      - name: Compress files
        run: zip -r build/windows.zip build/windows
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows.zip
          if-no-files-found: error
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows.zip
      - name: Deploy to Itch.io
        run: butler push build/windows.zip ${{vars.ITCHIO_USERNAME}}/${{vars.ITCHIO_GAME}}:windows

  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Export
        run: |
          mkdir -v -p build/web
          godot -v --export-release --headless "Web" build/web/index.html
      - name: Compress files
        run: zip -r build/web.zip build/web
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web.zip
          if-no-files-found: error
      - name: Deploy to Itch.io
        run: butler push build/web.zip ${{vars.ITCHIO_USERNAME}}/${{vars.ITCHIO_GAME}}:web
